/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.gatoDao;
import br.ulbra.dao.usuarioDao;
import br.ulbra.model.gato;
import br.ulbra.model.usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sun.swing.SwingAccessor;

/**
 *
 * @author Jeferson Leon
 */
public class frCadGato extends javax.swing.JFrame {

    /**
     * Creates new form frCadUsu
     */
    public frCadGato() {
        initComponents();
        setLocationRelativeTo(null);
        habilitarB(1);
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        
        gatoDao pdao = new gatoDao();

        for (gato g : pdao.read()) {
            String vacinado = "NAO", microchip = "NAO";
            if (g.isVacinadoGato()){
                vacinado = "SIM";
            }
            if (g.isMicrochipGato()){
                microchip = "SIM";
            }
            
            modelo.addRow(new Object[]{
                g.getIdGato(),
                g.getNomeGato(),
                g.getGeneroGato(),
                g.getRacaGato(),
                g.getNascimentoGato(),
                g.getTamanhoGato(),
                vacinado,
                g.getCorGato(),
                g.getPesoGato(),
                microchip,
                g.getDescricaoGato()
            });

        }

    }

    public void readForDesc(String nome) {

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        gatoDao pdao = new gatoDao();

        for (gato g : pdao.readForDesc(nome)) {

            String vacinado = "NAO", microchip = "NAO";
            if (g.isVacinadoGato()){
                vacinado = "SIM";
            }
            if (g.isMicrochipGato()){
                microchip = "SIM";
            }
            
            modelo.addRow(new Object[]{
                g.getIdGato(),
                g.getNomeGato(),
                g.getGeneroGato(),
                g.getRacaGato(),
                g.getNascimentoGato(),
                g.getTamanhoGato(),
                vacinado,
                g.getCorGato(),
                g.getPesoGato(),
                microchip,
                g.getDescricaoGato()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TabCad = new javax.swing.JTabbedPane();
        tabcad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EDID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EDNOME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BTNOVO = new javax.swing.JButton();
        BTSALVAR = new javax.swing.JButton();
        BTEDITAR = new javax.swing.JButton();
        BTEXCLUIR = new javax.swing.JButton();
        BTCANCELAR = new javax.swing.JButton();
        EDRACA = new javax.swing.JTextField();
        LISTAGENERO = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        EDDATANASCIMENTO = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        EDCOR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CBVACINADO = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        EDTAMANHO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CBMICROCHIP = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EDPESO = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        EDDESC = new javax.swing.JTextArea();
        tabcon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btPrimeiro = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        BTPESQUISAR = new javax.swing.JButton();
        edNomep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabcad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE GATOS");
        tabcad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        tabcad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 58, -1, -1));

        EDID.setEditable(false);
        tabcad.add(EDID, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 53, 85, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOME");
        tabcad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        EDNOME.setEditable(false);
        tabcad.add(EDNOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 124, 202, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("GENERO");
        tabcad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 166, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RAÇA");
        jLabel5.setToolTipText("");
        tabcad.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 233, -1, -1));

        BTNOVO.setBackground(new java.awt.Color(51, 51, 51));
        BTNOVO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTNOVO.setForeground(new java.awt.Color(255, 255, 255));
        BTNOVO.setText("NOVO");
        BTNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOVOActionPerformed(evt);
            }
        });
        tabcad.add(BTNOVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        BTSALVAR.setBackground(new java.awt.Color(51, 255, 0));
        BTSALVAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTSALVAR.setForeground(new java.awt.Color(255, 255, 255));
        BTSALVAR.setText("SALVAR");
        BTSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSALVARActionPerformed(evt);
            }
        });
        tabcad.add(BTSALVAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        BTEDITAR.setBackground(new java.awt.Color(51, 51, 51));
        BTEDITAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTEDITAR.setForeground(new java.awt.Color(255, 255, 255));
        BTEDITAR.setText("EDITAR");
        BTEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEDITARActionPerformed(evt);
            }
        });
        tabcad.add(BTEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 101, -1));

        BTEXCLUIR.setBackground(new java.awt.Color(51, 51, 51));
        BTEXCLUIR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTEXCLUIR.setForeground(new java.awt.Color(255, 255, 255));
        BTEXCLUIR.setText("EXCLUIR");
        BTEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEXCLUIRActionPerformed(evt);
            }
        });
        tabcad.add(BTEXCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        BTCANCELAR.setBackground(new java.awt.Color(51, 51, 51));
        BTCANCELAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTCANCELAR.setForeground(new java.awt.Color(255, 255, 255));
        BTCANCELAR.setText("CANCELAR");
        BTCANCELAR.setEnabled(false);
        BTCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCANCELARActionPerformed(evt);
            }
        });
        tabcad.add(BTCANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        EDRACA.setEditable(false);
        tabcad.add(EDRACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 256, 202, 32));

        LISTAGENERO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMININO" }));
        LISTAGENERO.setEnabled(false);
        tabcad.add(LISTAGENERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 189, 202, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DATA DE NASCIMENTO");
        jLabel7.setToolTipText("");
        tabcad.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 297, -1, -1));

        EDDATANASCIMENTO.setEditable(false);
        tabcad.add(EDDATANASCIMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 324, 202, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TAMANHO");
        tabcad.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        EDCOR.setEditable(false);
        tabcad.add(EDCOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 205, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("VACINADO?");
        tabcad.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        CBVACINADO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CBVACINADO.setText("SIM");
        CBVACINADO.setEnabled(false);
        CBVACINADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBVACINADOActionPerformed(evt);
            }
        });
        tabcad.add(CBVACINADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("COR");
        tabcad.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        EDTAMANHO.setEditable(false);
        tabcad.add(EDTAMANHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 210, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("MICROCHIPADO?");
        tabcad.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        CBMICROCHIP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CBMICROCHIP.setText("SIM");
        CBMICROCHIP.setEnabled(false);
        CBMICROCHIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMICROCHIPActionPerformed(evt);
            }
        });
        tabcad.add(CBMICROCHIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("DESCRIÇÃO");
        tabcad.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("PESO");
        tabcad.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        EDPESO.setEditable(false);
        tabcad.add(EDPESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 205, 30));

        jScrollPane3.setToolTipText("");

        EDDESC.setColumns(20);
        EDDESC.setLineWrap(true);
        EDDESC.setRows(5);
        jScrollPane3.setViewportView(EDDESC);

        tabcad.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 180, 210));

        TabCad.addTab("Cadastro", tabcad);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "GENERO", "RAÇA", "DATA DE NASCIMENTO", "TAMANHO", "VACINADO?", "COR", "PESO", "MICROCHIPADO?", "DESCRIÇÃO"
            }
        ));
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        btPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primeiro.png"))); // NOI18N
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        btAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior.png"))); // NOI18N
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proximo.png"))); // NOI18N
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultimo.png"))); // NOI18N
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        BTPESQUISAR.setBackground(new java.awt.Color(0, 102, 255));
        BTPESQUISAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTPESQUISAR.setForeground(new java.awt.Color(255, 255, 255));
        BTPESQUISAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        BTPESQUISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPESQUISARActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nome:");

        javax.swing.GroupLayout tabconLayout = new javax.swing.GroupLayout(tabcon);
        tabcon.setLayout(tabconLayout);
        tabconLayout.setHorizontalGroup(
            tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(tabconLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btUltimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabconLayout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(edNomep, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTPESQUISAR)
                .addGap(43, 43, 43))
        );
        tabconLayout.setVerticalGroup(
            tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabconLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTPESQUISAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edNomep))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btUltimo)
                    .addComponent(btProximo)
                    .addComponent(btAnterior)
                    .addComponent(btPrimeiro))
                .addGap(5, 5, 5))
        );

        TabCad.addTab("Consulta", tabcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabCad, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabCad)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void habilitarB(int op) {
        switch (op) {
            case 1: //algo -> só novo
                BTNOVO.setEnabled(true);
                BTSALVAR.setEnabled(false);
                BTPESQUISAR.setEnabled(true);
                BTEDITAR.setEnabled(false);
                BTEXCLUIR.setEnabled(false);
                BTCANCELAR.setEnabled(false);

                EDNOME.setEditable(false);
                LISTAGENERO.setEnabled(false);
                EDRACA.setEditable(false);
                EDDATANASCIMENTO.setEditable(false);
                EDTAMANHO.setEditable(false);
                CBVACINADO.setEnabled(false);
                EDCOR.setEditable(false);
                EDPESO.setEditable(false);
                CBMICROCHIP.setEnabled(false);
                EDDESC.setEditable(false);

                EDNOME.requestFocus();
                break;
            case 2: //novo -> salvar
                BTNOVO.setEnabled(false);
                BTSALVAR.setEnabled(true);
                BTPESQUISAR.setEnabled(true);
                BTEDITAR.setEnabled(false);
                BTEXCLUIR.setEnabled(false);
                BTCANCELAR.setEnabled(true);

                EDNOME.setEditable(true);
                LISTAGENERO.setEnabled(true);
                EDRACA.setEditable(true);
                EDDATANASCIMENTO.setEditable(true);
                EDTAMANHO.setEditable(true);
                CBVACINADO.setEnabled(true);
                EDCOR.setEditable(true);
                EDPESO.setEditable(true);
                CBMICROCHIP.setEnabled(true);
                EDDESC.setEditable(true);

                EDNOME.requestFocus();
                break;
            case 3: //selecionar algo na tabela
                BTNOVO.setEnabled(false);
                BTSALVAR.setEnabled(false);
                BTPESQUISAR.setEnabled(true);
                BTEDITAR.setEnabled(true);
                BTEXCLUIR.setEnabled(true);
                BTCANCELAR.setEnabled(true);

                EDNOME.setEditable(true);
                LISTAGENERO.setEnabled(true);
                EDRACA.setEditable(true);
                EDDATANASCIMENTO.setEditable(true);
                EDTAMANHO.setEditable(true);
                CBVACINADO.setEnabled(true);
                EDCOR.setEditable(true);
                EDPESO.setEditable(true);
                CBMICROCHIP.setEnabled(true);
                EDDESC.setEditable(true);

                EDNOME.requestFocus();
                break;
        }
    }
    private void BTNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOVOActionPerformed
        habilitarB(2);
        EDID.setText("");
        EDNOME.setText("");
        LISTAGENERO.setSelectedIndex(0);
        EDRACA.setText("");
        EDDATANASCIMENTO.setText("");
        EDTAMANHO.setText("");
        CBVACINADO.setSelected(false);
        EDCOR.setText("");
        EDPESO.setText("");
        CBMICROCHIP.setSelected(false);
        EDDESC.setText("");

        EDNOME.requestFocus();
    }//GEN-LAST:event_BTNOVOActionPerformed
    private void irTab() {
        if (tabela.getSelectedRow() != -1) {

            EDID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            EDNOME.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            LISTAGENERO.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            EDRACA.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            EDDATANASCIMENTO.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
            EDTAMANHO.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
            boolean vacinado = false;
            if (tabela.getValueAt(tabela.getSelectedRow(), 6).toString() == "SIM") {
                vacinado = true;
            }
            CBVACINADO.setSelected(vacinado);
            EDCOR.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
            EDPESO.setText(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
            boolean microchip = false;
            if (tabela.getValueAt(tabela.getSelectedRow(), 9).toString() == "SIM") {
                microchip = true;
            }
            CBMICROCHIP.setSelected(microchip);
            EDDESC.setText(tabela.getValueAt(tabela.getSelectedRow(), 10).toString());
        }
    }
    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (tabela.getSelectedRow() != -1) {

            EDID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            EDNOME.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            LISTAGENERO.setSelectedItem(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            EDRACA.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            EDDATANASCIMENTO.setText(tabela.getValueAt(tabela.getSelectedRow(), 4).toString());
            EDTAMANHO.setText(tabela.getValueAt(tabela.getSelectedRow(), 5).toString());
            boolean vacinado = false;
            if (tabela.getValueAt(tabela.getSelectedRow(), 6).toString() == "SIM") {
                vacinado = true;
            }
            CBVACINADO.setSelected(vacinado);
            EDCOR.setText(tabela.getValueAt(tabela.getSelectedRow(), 7).toString());
            EDPESO.setText(tabela.getValueAt(tabela.getSelectedRow(), 8).toString());
            boolean microchip = false;
            if (tabela.getValueAt(tabela.getSelectedRow(), 9).toString() == "SIM") {
                microchip = true;
            }
            CBMICROCHIP.setSelected(microchip);
            EDDESC.setText(tabela.getValueAt(tabela.getSelectedRow(), 10).toString());
            habilitarB(3);
            TabCad.setSelectedIndex(0);

        }

    }//GEN-LAST:event_tabelaMouseClicked

    private void BTEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEXCLUIRActionPerformed
        if (tabela.getSelectedRow() != -1) {

            gato g = new gato();
            gatoDao dao = new gatoDao();

            g.setIdGato((int) tabela.getValueAt(tabela.getSelectedRow(), 0));

            dao.delete(g); //deleta fodase

            EDID.setText("");
            EDNOME.setText("");
            LISTAGENERO.setSelectedIndex(0);
            EDRACA.setText("");
            EDDATANASCIMENTO.setText("");
            EDTAMANHO.setText("");
            CBVACINADO.setSelected(false);
            EDCOR.setText("");
            EDPESO.setText("");
            CBMICROCHIP.setSelected(false);
            EDDESC.setText("");

            readJTable();
            habilitarB(1);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

    }//GEN-LAST:event_BTEXCLUIRActionPerformed

    private void BTEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEDITARActionPerformed
        if (tabela.getSelectedRow() != -1) {

            gato g = new gato();
            gatoDao dao = new gatoDao();

            g.setIdGato((int) tabela.getValueAt(tabela.getSelectedRow(), 0));
            g.setNomeGato(EDNOME.getText());
            g.setGeneroGato((String) LISTAGENERO.getSelectedItem());
            g.setRacaGato(EDRACA.getText());
            g.setNascimentoGato(EDDATANASCIMENTO.getText());
            g.setTamanhoGato(Double.parseDouble(EDTAMANHO.getText()));
            g.setVacinadoGato(CBVACINADO.isSelected());
            g.setCorGato(EDCOR.getText());
            g.setPesoGato(Double.parseDouble(EDPESO.getText()));
            g.setMicrochipGato(CBMICROCHIP.isSelected());
            g.setDescricaoGato(EDDESC.getText());

            dao.update(g); //update no id

            EDID.setText("");
            EDNOME.setText("");
            LISTAGENERO.setSelectedIndex(0);
            EDRACA.setText("");
            EDDATANASCIMENTO.setText("");
            EDTAMANHO.setText("");
            CBVACINADO.setSelected(false);
            EDCOR.setText("");
            EDPESO.setText("");
            CBMICROCHIP.setSelected(false);
            EDDESC.setText("");

            readJTable();
            habilitarB(1);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para editar.");
        }
    }//GEN-LAST:event_BTEDITARActionPerformed

    private void BTPESQUISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPESQUISARActionPerformed
        readForDesc(edNomep.getText());
    }//GEN-LAST:event_BTPESQUISARActionPerformed

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
        int numeroLinhas = tabela.getRowCount();
        if (numeroLinhas > 0) {
            tabela.setRowSelectionInterval(0, 0);
            irTab();
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        int numeroLinhas = tabela.getRowCount();
        if (numeroLinhas > 0) {
            tabela.setRowSelectionInterval(numeroLinhas - 1, numeroLinhas - 1);
            irTab();
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void BTSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSALVARActionPerformed

        gato g = new gato();
        g.setNomeGato(EDNOME.getText());
        g.setGeneroGato((String) LISTAGENERO.getSelectedItem());
        g.setRacaGato(EDRACA.getText());
        g.setNascimentoGato(EDDATANASCIMENTO.getText());
        g.setTamanhoGato(Double.parseDouble(EDTAMANHO.getText()));
        g.setVacinadoGato(CBVACINADO.isSelected());
        g.setCorGato(EDCOR.getText());
        g.setPesoGato(Double.parseDouble(EDPESO.getText()));
        g.setMicrochipGato(CBMICROCHIP.isSelected());
        g.setDescricaoGato(EDDESC.getText());

        gatoDao dao = new gatoDao();
        dao.create(g); //cria o treco
        
        EDID.setText("");
        EDNOME.setText("");
        LISTAGENERO.setSelectedIndex(0);
        EDRACA.setText("");
        EDDATANASCIMENTO.setText("");
        EDTAMANHO.setText("");
        CBVACINADO.setSelected(false);
        EDCOR.setText("");
        EDPESO.setText("");
        CBMICROCHIP.setSelected(false);
        EDDESC.setText("");
        
        habilitarB(1);
        readJTable();
        TabCad.setSelectedIndex(1);
    }//GEN-LAST:event_BTSALVARActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        int numeroLinhas = tabela.getRowCount();
        int ls = tabela.getSelectedRow();
        if (numeroLinhas > 0 && ls != 0) {
            tabela.setRowSelectionInterval(ls - 1, ls - 1);
            irTab();
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        int numeroLinhas = tabela.getRowCount();
        int ls = tabela.getSelectedRow();
        if (numeroLinhas > 0 && ls < numeroLinhas - 1) {
            tabela.setRowSelectionInterval(ls + 1, ls + 1);
            irTab();
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void BTCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCANCELARActionPerformed
        EDID.setText("");
        EDNOME.setText("");
        LISTAGENERO.setSelectedIndex(0);
        EDRACA.setText("");
        EDDATANASCIMENTO.setText("");
        EDTAMANHO.setText("");
        CBVACINADO.setSelected(false);
        EDCOR.setText("");
        EDPESO.setText("");
        CBMICROCHIP.setSelected(false);
        EDDESC.setText("");
        
        habilitarB(1);
    }//GEN-LAST:event_BTCANCELARActionPerformed

    private void CBVACINADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBVACINADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBVACINADOActionPerformed

    private void CBMICROCHIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMICROCHIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBMICROCHIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frCadGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frCadGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frCadGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frCadGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frCadGato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCANCELAR;
    private javax.swing.JButton BTEDITAR;
    private javax.swing.JButton BTEXCLUIR;
    private javax.swing.JButton BTNOVO;
    private javax.swing.JButton BTPESQUISAR;
    private javax.swing.JButton BTSALVAR;
    private javax.swing.JCheckBox CBMICROCHIP;
    private javax.swing.JCheckBox CBVACINADO;
    private javax.swing.JTextField EDCOR;
    private javax.swing.JFormattedTextField EDDATANASCIMENTO;
    private javax.swing.JTextArea EDDESC;
    private javax.swing.JTextField EDID;
    private javax.swing.JTextField EDNOME;
    private javax.swing.JTextField EDPESO;
    private javax.swing.JTextField EDRACA;
    private javax.swing.JTextField EDTAMANHO;
    private javax.swing.JComboBox<String> LISTAGENERO;
    private javax.swing.JTabbedPane TabCad;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btUltimo;
    private javax.swing.JTextField edNomep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel tabcad;
    private javax.swing.JPanel tabcon;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
