/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.dao.usuarioDao;
import br.ulbra.model.usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import sun.swing.SwingAccessor;

/**
 *
 * @author Jeferson Leon
 */
public class frCadUsu extends javax.swing.JFrame {

    /**
     * Creates new form frCadUsu
     */
    public frCadUsu() {
        initComponents();
        setLocationRelativeTo(null);
        habilitarB(1);
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        usuarioDao pdao = new usuarioDao();

        for (usuario u : pdao.read()) {

            modelo.addRow(new Object[]{
                u.getIdUsu(),
                u.getNomeUsu(),
                u.getEmailUsu(),
                u.getSenhaUsu()
            });

        }

    }

    public void readForDesc(String nome) {

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        usuarioDao pdao = new usuarioDao();

        for (usuario u : pdao.readForDesc(nome)) {

            modelo.addRow(new Object[]{
                u.getIdUsu(),
                u.getNomeUsu(),
                u.getEmailUsu(),
                u.getSenhaUsu()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TabCad = new javax.swing.JTabbedPane();
        tabcad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EDID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EDNOME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EDEMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTNOVO = new javax.swing.JButton();
        BTSALVAR = new javax.swing.JButton();
        BTEDITAR = new javax.swing.JButton();
        BTEXCLUIR = new javax.swing.JButton();
        BTCANCELAR = new javax.swing.JButton();
        EDSENHA = new javax.swing.JTextField();
        tabcon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        btPrimeiro = new javax.swing.JButton();
        btAnterior = new javax.swing.JButton();
        btProximo = new javax.swing.JButton();
        btUltimo = new javax.swing.JButton();
        BTPESQUISAR = new javax.swing.JButton();
        edNomep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE USUARIOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");

        EDID.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOME");

        EDNOME.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("E-MAIL");

        EDEMAIL.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SENHA");

        BTNOVO.setBackground(new java.awt.Color(51, 51, 51));
        BTNOVO.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTNOVO.setForeground(new java.awt.Color(255, 255, 255));
        BTNOVO.setText("NOVO");
        BTNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOVOActionPerformed(evt);
            }
        });

        BTSALVAR.setBackground(new java.awt.Color(51, 255, 0));
        BTSALVAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTSALVAR.setForeground(new java.awt.Color(255, 255, 255));
        BTSALVAR.setText("SALVAR");
        BTSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSALVARActionPerformed(evt);
            }
        });

        BTEDITAR.setBackground(new java.awt.Color(51, 51, 51));
        BTEDITAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTEDITAR.setForeground(new java.awt.Color(255, 255, 255));
        BTEDITAR.setText("EDITAR");
        BTEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEDITARActionPerformed(evt);
            }
        });

        BTEXCLUIR.setBackground(new java.awt.Color(51, 51, 51));
        BTEXCLUIR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTEXCLUIR.setForeground(new java.awt.Color(255, 255, 255));
        BTEXCLUIR.setText("EXCLUIR");
        BTEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTEXCLUIRActionPerformed(evt);
            }
        });

        BTCANCELAR.setBackground(new java.awt.Color(51, 51, 51));
        BTCANCELAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTCANCELAR.setForeground(new java.awt.Color(255, 255, 255));
        BTCANCELAR.setText("CANCELAR");
        BTCANCELAR.setEnabled(false);
        BTCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCANCELARActionPerformed(evt);
            }
        });

        EDSENHA.setEditable(false);

        javax.swing.GroupLayout tabcadLayout = new javax.swing.GroupLayout(tabcad);
        tabcad.setLayout(tabcadLayout);
        tabcadLayout.setHorizontalGroup(
            tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabcadLayout.createSequentialGroup()
                .addGroup(tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabcadLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabcadLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EDEMAIL, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabcadLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(BTNOVO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTSALVAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTEXCLUIR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTCANCELAR))
                            .addComponent(EDNOME)
                            .addGroup(tabcadLayout.createSequentialGroup()
                                .addGroup(tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(tabcadLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(EDID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(EDSENHA))))
                .addGap(139, 139, 139))
        );
        tabcadLayout.setVerticalGroup(
            tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabcadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EDID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EDNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EDEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EDSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(tabcadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNOVO)
                    .addComponent(BTSALVAR)
                    .addComponent(BTEXCLUIR)
                    .addComponent(BTEDITAR)
                    .addComponent(BTCANCELAR))
                .addGap(39, 39, 39))
        );

        TabCad.addTab("Cadastro", tabcad);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "E-MAIL", "SENHA"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        btPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/primeiro.png"))); // NOI18N
        btPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrimeiroActionPerformed(evt);
            }
        });

        btAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anterior.png"))); // NOI18N
        btAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnteriorActionPerformed(evt);
            }
        });

        btProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proximo.png"))); // NOI18N
        btProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProximoActionPerformed(evt);
            }
        });

        btUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ultimo.png"))); // NOI18N
        btUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUltimoActionPerformed(evt);
            }
        });

        BTPESQUISAR.setBackground(new java.awt.Color(0, 102, 255));
        BTPESQUISAR.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        BTPESQUISAR.setForeground(new java.awt.Color(255, 255, 255));
        BTPESQUISAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        BTPESQUISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPESQUISARActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nome:");

        javax.swing.GroupLayout tabconLayout = new javax.swing.GroupLayout(tabcon);
        tabcon.setLayout(tabconLayout);
        tabconLayout.setHorizontalGroup(
            tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabconLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(tabconLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btPrimeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btProximo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btUltimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabconLayout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(edNomep, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTPESQUISAR)
                .addGap(43, 43, 43))
        );
        tabconLayout.setVerticalGroup(
            tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabconLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTPESQUISAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edNomep))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btUltimo)
                    .addComponent(btProximo)
                    .addComponent(btAnterior)
                    .addComponent(btPrimeiro))
                .addGap(5, 5, 5))
        );

        TabCad.addTab("Consulta", tabcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabCad, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabCad)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void habilitarB(int op) {
        switch (op) {
            case 1: //algo -> só novo
                BTNOVO.setEnabled(true);
                BTSALVAR.setEnabled(false);
                BTPESQUISAR.setEnabled(true);
                BTEDITAR.setEnabled(false);
                BTEXCLUIR.setEnabled(false);
                BTCANCELAR.setEnabled(false);
                
                EDNOME.setEditable(false);
                EDEMAIL.setEditable(false);
                EDSENHA.setEditable(false);
                
                EDNOME.requestFocus();
                break;
            case 2: //novo -> salvar
                BTNOVO.setEnabled(false);
                BTSALVAR.setEnabled(true);
                BTPESQUISAR.setEnabled(true);
                BTEDITAR.setEnabled(false);
                BTEXCLUIR.setEnabled(false);
                BTCANCELAR.setEnabled(true);
                
                EDNOME.setEditable(true);
                EDEMAIL.setEditable(true);
                EDSENHA.setEditable(true);
                
                EDNOME.requestFocus();
                break;
            case 3: //selecionar algo na tabela
                BTNOVO.setEnabled(false);
                BTSALVAR.setEnabled(false);
                BTPESQUISAR.setEnabled(true);
                BTEDITAR.setEnabled(true);
                BTEXCLUIR.setEnabled(true);
                 BTCANCELAR.setEnabled(true);
                 
                 EDNOME.setEditable(true);
                EDEMAIL.setEditable(true);
                EDSENHA.setEditable(true);
                 
                EDNOME.requestFocus();
                break;
        }
    }
    private void BTNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOVOActionPerformed
        habilitarB(2);
        EDID.setText("");
        EDNOME.setText("");
        EDEMAIL.setText("");
        EDSENHA.setText("");
        EDNOME.requestFocus();
    }//GEN-LAST:event_BTNOVOActionPerformed
    private void irTab() {
        if (tabela.getSelectedRow() != -1) {

            EDID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            EDNOME.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            EDEMAIL.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            EDSENHA.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());

        }
    }
    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        if (tabela.getSelectedRow() != -1) {

            EDID.setText(tabela.getValueAt(tabela.getSelectedRow(), 0).toString());
            EDNOME.setText(tabela.getValueAt(tabela.getSelectedRow(), 1).toString());
            EDEMAIL.setText(tabela.getValueAt(tabela.getSelectedRow(), 2).toString());
            EDSENHA.setText(tabela.getValueAt(tabela.getSelectedRow(), 3).toString());
            habilitarB(3);
            TabCad.setSelectedIndex(0);

        }

    }//GEN-LAST:event_tabelaMouseClicked

    private void BTEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEXCLUIRActionPerformed
        if (tabela.getSelectedRow() != -1) {

            usuario u = new usuario();
            usuarioDao dao = new usuarioDao();

            u.setIdUsu((int) tabela.getValueAt(tabela.getSelectedRow(), 0));

            dao.delete(u);

            EDID.setText("");
            EDNOME.setText("");
            EDEMAIL.setText("");
            EDSENHA.setText("");

            readJTable();
            habilitarB(1);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

    }//GEN-LAST:event_BTEXCLUIRActionPerformed

    private void BTEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTEDITARActionPerformed
        if (tabela.getSelectedRow() != -1) {

            usuario u = new usuario();
            usuarioDao dao = new usuarioDao();

            u.setNomeUsu(EDNOME.getText());
            u.setEmailUsu(EDEMAIL.getText());
            u.setSenhaUsu(EDSENHA.getText());
            u.setIdUsu((int) tabela.getValueAt(tabela.getSelectedRow(), 0));
            dao.update(u);

            EDID.setText("");
            EDNOME.setText("");
            EDEMAIL.setText("");
            EDSENHA.setText("");

            readJTable();
            habilitarB(1);
        }  else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para editar.");
        }
    }//GEN-LAST:event_BTEDITARActionPerformed

    private void BTPESQUISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPESQUISARActionPerformed
        readForDesc(edNomep.getText());
    }//GEN-LAST:event_BTPESQUISARActionPerformed

    private void btPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrimeiroActionPerformed
        int numeroLinhas = tabela.getRowCount();
        if (numeroLinhas > 0) {
            tabela.setRowSelectionInterval(0, 0);
            irTab();
        }
    }//GEN-LAST:event_btPrimeiroActionPerformed

    private void btUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUltimoActionPerformed
        int numeroLinhas = tabela.getRowCount();
        if (numeroLinhas > 0) {
            tabela.setRowSelectionInterval(numeroLinhas - 1, numeroLinhas - 1);
            irTab();
        }
    }//GEN-LAST:event_btUltimoActionPerformed

    private void BTSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSALVARActionPerformed

        usuario u = new usuario();
        u.setNomeUsu(EDNOME.getText());
        u.setEmailUsu(EDEMAIL.getText());
        u.setSenhaUsu(EDSENHA.getText());

        usuarioDao dao = new usuarioDao();
        dao.create(u);
        EDNOME.setText("");
        EDEMAIL.setText("");
        EDSENHA.setText("");
        habilitarB(1);
        readJTable();
        TabCad.setSelectedIndex(1);
    }//GEN-LAST:event_BTSALVARActionPerformed

    private void btAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnteriorActionPerformed
        int numeroLinhas = tabela.getRowCount();
        int ls = tabela.getSelectedRow();
        if (numeroLinhas > 0 && ls != 0) {
            tabela.setRowSelectionInterval(ls - 1, ls - 1);
            irTab();
        }
    }//GEN-LAST:event_btAnteriorActionPerformed

    private void btProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProximoActionPerformed
        int numeroLinhas = tabela.getRowCount();
        int ls = tabela.getSelectedRow();
        if (numeroLinhas > 0 && ls < numeroLinhas - 1) {
            tabela.setRowSelectionInterval(ls + 1, ls + 1);
            irTab();
        }
    }//GEN-LAST:event_btProximoActionPerformed

    private void BTCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCANCELARActionPerformed
        EDNOME.setText("");
        EDEMAIL.setText("");
        EDSENHA.setText("");
        
        habilitarB(1);
    }//GEN-LAST:event_BTCANCELARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frCadUsu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frCadUsu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCANCELAR;
    private javax.swing.JButton BTEDITAR;
    private javax.swing.JButton BTEXCLUIR;
    private javax.swing.JButton BTNOVO;
    private javax.swing.JButton BTPESQUISAR;
    private javax.swing.JButton BTSALVAR;
    private javax.swing.JTextField EDEMAIL;
    private javax.swing.JTextField EDID;
    private javax.swing.JTextField EDNOME;
    private javax.swing.JTextField EDSENHA;
    private javax.swing.JTabbedPane TabCad;
    private javax.swing.JButton btAnterior;
    private javax.swing.JButton btPrimeiro;
    private javax.swing.JButton btProximo;
    private javax.swing.JButton btUltimo;
    private javax.swing.JTextField edNomep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel tabcad;
    private javax.swing.JPanel tabcon;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
